/**
 * Campus Flow - Frontend Production Build Script
 * Builds static assets for Vercel edge deployment and generates client-side bundles.
 */

const fs = require('fs');
const path = require('path');

const ROOT_DIR = path.resolve(__dirname, '..');
const STATIC_DIR = path.join(ROOT_DIR, 'static');
const DIST_DIR = path.join(ROOT_DIR, 'dist');
const VERCEL_JSON_PATH = path.join(ROOT_DIR, 'vercel.json');

console.log('[Campus Flow Build] Initializing frontend build pipeline...');

// 1. Resolve Backend / API URL from environment variables
const backendUrl = (
    process.env.VITE_API_URL ||
    process.env.BACKEND_URL ||
    process.env.RAILWAY_URL ||
    process.env.NEXT_PUBLIC_API_URL ||
    process.env.REACT_APP_API_URL ||
    ''
).trim().replace(/\/+$/, '');

console.log(`[Campus Flow Build] Configured Backend URL: ${backendUrl || '(relative / fallback to proxy)'}`);

// 2. Prepare Clean dist directory
if (fs.existsSync(DIST_DIR)) {
    fs.rmSync(DIST_DIR, { recursive: true, force: true });
}
fs.mkdirSync(DIST_DIR, { recursive: true });
fs.mkdirSync(path.join(DIST_DIR, 'static'), { recursive: true });

// Helper to copy directory recursively
function copyDirectorySync(src, dest) {
    if (!fs.existsSync(src)) return;
    fs.mkdirSync(dest, { recursive: true });
    const entries = fs.readdirSync(src, { withFileTypes: true });
    for (const entry of entries) {
        const srcPath = path.join(src, entry.name);
        const destPath = path.join(dest, entry.name);
        if (entry.isDirectory()) {
            copyDirectorySync(srcPath, destPath);
        } else {
            fs.copyFileSync(srcPath, destPath);
        }
    }
}

// 3. Copy static directory into dist/static and dist
if (fs.existsSync(STATIC_DIR)) {
    console.log('[Campus Flow Build] Copying static assets to dist/static...');
    copyDirectorySync(STATIC_DIR, path.join(DIST_DIR, 'static'));
    copyDirectorySync(STATIC_DIR, DIST_DIR);
}

// 4. Generate runtime env-config.js for client scripts
const envConfigContent = `// Auto-generated by Campus Flow build pipeline
window.CAMPUS_FLOW_API_URL = ${JSON.stringify(backendUrl)};
window.API_URL = ${JSON.stringify(backendUrl)};
`;
fs.writeFileSync(path.join(DIST_DIR, 'env-config.js'), envConfigContent, 'utf8');
const jsTargetDir = path.join(DIST_DIR, 'static', 'js');
if (fs.existsSync(jsTargetDir)) {
    fs.writeFileSync(path.join(jsTargetDir, 'env-config.js'), envConfigContent, 'utf8');
}

// 5. Generate high-performance index.html portal in dist
const indexHtmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Campus Flow - College Event Management Platform</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <script src="/env-config.js"></script>
    <style>
        body {
            min-height: 100vh;
            display: flex;
            flex-direction: column;
            background: linear-gradient(135deg, #090d16 0%, #111827 50%, #0b1120 100%);
            color: #f8fafc;
            font-family: 'Inter', sans-serif;
        }
        .hero-glow {
            position: absolute;
            width: 450px;
            height: 450px;
            border-radius: 50%;
            background: radial-gradient(circle, rgba(59, 130, 246, 0.18) 0%, rgba(99, 102, 241, 0.08) 50%, transparent 70%);
            top: 20%;
            left: 50%;
            transform: translate(-50%, -20%);
            filter: blur(60px);
            pointer-events: none;
        }
        .portal-card {
            background: rgba(17, 24, 39, 0.75);
            backdrop-filter: blur(16px);
            border: 1px solid rgba(255, 255, 255, 0.1);
            border-radius: 20px;
            box-shadow: 0 20px 40px -15px rgba(0, 0, 0, 0.5);
            transition: all 0.3s ease;
        }
        .portal-card:hover {
            transform: translateY(-4px);
            border-color: rgba(59, 130, 246, 0.4);
        }
        .btn-glow {
            background: linear-gradient(135deg, #2563eb 0%, #4f46e5 100%);
            color: #fff;
            box-shadow: 0 10px 25px -5px rgba(37, 99, 235, 0.5);
            border: none;
        }
        .btn-glow:hover {
            background: linear-gradient(135deg, #1d4ed8 0%, #4338ca 100%);
            color: #fff;
            transform: translateY(-2px);
        }
    </style>
</head>
<body>
    <div class="hero-glow"></div>
    <header class="navbar navbar-expand-lg border-bottom border-dark py-3">
        <div class="container">
            <a class="navbar-brand text-white fw-bold d-flex align-items-center gap-2" href="/">
                <i class="bi bi-calendar2-event-fill text-primary fs-4"></i> Campus <span class="text-primary">Flow</span>
            </a>
            <div class="d-flex align-items-center gap-3">
                <span id="backendStatusBadge" class="badge bg-secondary-subtle text-secondary px-3 py-2 rounded-pill">
                    <span class="spinner-grow spinner-grow-sm me-1" style="width: 0.6rem; height: 0.6rem;"></span> Checking Backend
                </span>
            </div>
        </div>
    </header>

    <main class="container my-auto py-5">
        <div class="row justify-content-center text-center">
            <div class="col-lg-8">
                <span class="badge bg-primary-subtle text-primary border border-primary-subtle rounded-pill px-3 py-2 mb-3">
                    <i class="bi bi-stars me-1"></i> Unified College Event Platform
                </span>
                <h1 class="display-4 fw-extrabold mb-3">Campus Flow</h1>
                <p class="lead text-secondary mb-4 mx-auto" style="max-width: 620px;">
                    Centralized event discovery, direct UPI payments, fraud-resistant transaction verification, QR attendance, and automated digital certificates.
                </p>
                <div class="d-flex flex-wrap justify-content-center gap-3 mb-5">
                    <a id="enterAppBtn" href="/events" class="btn btn-glow btn-lg px-4 py-2 fw-semibold">
                        <i class="bi bi-compass me-2"></i>Discover Events
                    </a>
                    <a id="loginBtn" href="/login" class="btn btn-outline-light btn-lg px-4 py-2 fw-semibold">
                        <i class="bi bi-box-arrow-in-right me-2"></i>Sign In
                    </a>
                </div>

                <div class="row g-4 text-start">
                    <div class="col-md-4">
                        <div class="portal-card p-4 h-100">
                            <i class="bi bi-mortarboard fs-2 text-primary mb-3 d-block"></i>
                            <h5 class="fw-bold mb-2">Student Vault</h5>
                            <p class="small text-secondary mb-0">Browse events, register with team members, upload payment receipts, and download verified certificates.</p>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="portal-card p-4 h-100">
                            <i class="bi bi-qr-code-scan fs-2 text-info mb-3 d-block"></i>
                            <h5 class="fw-bold mb-2">Organizer Scanner</h5>
                            <p class="small text-secondary mb-0">Instant QR camera ticket verification, manual attendance overrides, and live participant tracking.</p>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="portal-card p-4 h-100">
                            <i class="bi bi-award fs-2 text-warning mb-3 d-block"></i>
                            <h5 class="fw-bold mb-2">Faculty & HOD Hub</h5>
                            <p class="small text-secondary mb-0">Event approval workflows, automated capacity alerts, and departmental participation analytics.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

    <footer class="border-top border-dark py-4 text-center small text-secondary">
        <div class="container">
            &copy; ${new Date().getFullYear()} Campus Flow &bull; Hosted on Vercel Edge &amp; Railway
        </div>
    </footer>

    <script>
        // Check backend connectivity and configure dynamic links
        (function() {
            const apiBase = (window.CAMPUS_FLOW_API_URL || '').replace(/\\/+$/, '');
            const badge = document.getElementById('backendStatusBadge');
            const enterBtn = document.getElementById('enterAppBtn');
            const loginBtn = document.getElementById('loginBtn');

            if (apiBase) {
                enterBtn.href = apiBase + '/events';
                loginBtn.href = apiBase + '/login';
            }

            const healthUrl = apiBase ? (apiBase + '/health') : '/health';
            fetch(healthUrl, { cache: 'no-store' })
                .then(r => r.json())
                .then(data => {
                    if (data && (data.status === 'ok' || data.status === 'healthy')) {
                        badge.className = 'badge bg-success-subtle text-success px-3 py-2 rounded-pill border border-success-subtle';
                        badge.innerHTML = '<i class="bi bi-check-circle-fill me-1"></i> Backend Online';
                    }
                })
                .catch(() => {
                    badge.className = 'badge bg-warning-subtle text-warning px-3 py-2 rounded-pill border border-warning-subtle';
                    badge.innerHTML = '<i class="bi bi-activity me-1"></i> Standalone Edge Mode';
                });
        })();
    </script>
</body>
</html>
`;
fs.writeFileSync(path.join(DIST_DIR, 'index.html'), indexHtmlContent, 'utf8');

// 6. Update or generate vercel.json rewrites if backend URL is provided
try {
    let vercelConfig = {
        version: 2,
        cleanUrls: true,
        buildCommand: 'npm run build',
        installCommand: "echo 'Frontend build, skipping Python dependencies'",
        outputDirectory: 'dist',
        headers: [
            {
                source: '/static/(.*)',
                headers: [
                    {
                        key: 'Cache-Control',
                        value: 'public, max-age=31536000, immutable'
                    }
                ]
            }
        ]
    };

    if (fs.existsSync(VERCEL_JSON_PATH)) {
        try {
            vercelConfig = JSON.parse(fs.readFileSync(VERCEL_JSON_PATH, 'utf8'));
        } catch (e) {}
    }

    const targetBackend = backendUrl || 'https://web-production-b67d9.up.railway.app';
    vercelConfig.rewrites = [
        {
            source: '/static/:path*',
            destination: '/static/:path*'
        },
        {
            source: '/:path*',
            destination: `${targetBackend}/:path*`
        }
    ];

    fs.writeFileSync(path.join(DIST_DIR, 'vercel.json'), JSON.stringify(vercelConfig, null, 2), 'utf8');
    fs.writeFileSync(VERCEL_JSON_PATH, JSON.stringify(vercelConfig, null, 2), 'utf8');
    console.log('[Campus Flow Build] Configured vercel.json rewrites pointing to backend:', targetBackend);
} catch (vErr) {
    console.warn('[Campus Flow Build] Note updating vercel.json:', vErr.message);
}

console.log('[Campus Flow Build] Build completed successfully into dist/');
